export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}

export enum EVENT_SOCKET {
  USER = 'USER',
  CASTLE = 'CASTLE',
  UNIT = 'UNIT',
  RESOURCE = 'RESOURCE',
  BUILDING = 'BUILDING',
  UPGRADE = 'UPGRADE',
  UPGRADE_DONE = 'UPGRADE_DONE',
  TRAINING = 'TRAINING',
  TRAINING_DONE = 'TRAINING_DONE',
}

export enum BUILDING {
  STORAGE = "STORAGE",
  DWELLINGS = "DWELLINGS",
}

export enum ENHANCE_TYPE {
  HP = "HP",
  ATTACK = "ATTACK",
  CARGO = "CARGO",
}