export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}

export enum EVENT_SOCKET {
  UNIT = 'UNIT',
  RESOURCE = 'RESOURCE',
  BUILDING = 'BUILDING',
  UPGRADE = 'UPGRADE',
  TRAINING = 'TRAINING',
  TRAINING_DONE = 'TRAINING_DONE',
}

export enum BUILDING {
  STORAGE = "STORAGE",
}